//Title:	dwHelpIKSpine.mel
//Author: 	David Walden
//		www.davidwalden.com
//		dwalden74@hotmail.com

//PROCEDURE THAT CREATES BACKBONE HELP WINDOW.
global proc dwHelpIKSpine()
{
if (`window -ex dwHelpIKSpineUI`)
	deleteUI dwHelpIKSpineUI;

window -t "IK-Spline Spine Help" -wh 500 425 dwHelpIKSpineUI;
	string $form = `formLayout`;
		string $scroll = `scrollLayout`;
			columnLayout;
				
				rowColumnLayout -nc 2 -cw 1 100 -cw 2 200;
					text -label "Author: " -font boldLabelFont;
					text -label "David Walden";
					text -label "";
					text -label "www.davidwalden.com";
					text -label "";
					text -label "dwalden74@hotmail.com";
					setParent..;
				
				text -label "" -h 30;
				
				text -label "  Usage:" -font boldLabelFont -align left -w 150;
				text -label "    Add the correct joint names to the text fields in the UI. Select other options as desired.";
				text -label "    The \"Get\" buttons will put the currently selected item into the relative text fields.";
				text -label "    Click on \"Create IK-Spline Spine\" at bottom of UI.";
				
				text -label "" -h 15;
				
				
				text -label "   About: " -font boldLabelFont;
				string $aboutText;
				$aboutText += "  July 6, 2004: I´ve introduced a new IK-Spline spine setup that takes advantage of the Advanced \n";
				$aboutText += "  Twist Options in the spline IK handle for Maya 5 and higher. This is a much easier and faster rig \n";
				$aboutText += "  than the older version. For users running Maya 4.5, the previous spine rig will be created instead. \n";
				$aboutText += "  The older version is taken from the Alias|Wavefront training DVD \"Integrating a Creature Animation\n";
				$aboutText += "  Rig within a Production Pipeline\", with some modifications. Note that the user can force the previous  \n";
				$aboutText += "  spine rig to be built, by selecting \"Force v4.5 spine\" under the Advanced options.\n";
				$aboutText += "\n";
				$aboutText += "  User also has the option of creating neck and head controls if desired. \n";
				text -label $aboutText -align left;
				
				text -label "" -h 25;
				
				text -label "   Notes: " -font boldLabelFont;
				string $noteText = "  This setup uses Maya´s IK Spline Handle Tool command with \"Auto Simplify Curve\" turned on.\n";
				$noteText += "   If the character´s spine joints are initially created in a typical S-curve, their rotations risk\n";
				$noteText += "   being modified to fit the simplified curve after executing this command. This can cause problems\n";
				$noteText += "   during the skinning process of the setup, and in transferring skin weights from one character to.\n";
				$noteText += "   another. Therefore, it is adviseable to create the character´s spine joints in a straight line.\n";
				$noteText += "   Ideally the user should be able to create the spine in any way desired.\n";
				
				$noteText += "\n";
				$noteText += "***Note: Upon completing the rig, mostly likely you´ll want to add a main \"Position\" controller, \n";
				$noteText += "         typically a NURBS circle or other spline control object, under which all \"*_Controls\"  \n";
				$noteText += "         groups are parented. If you are using the IK Spline Spine setup, do NOT parent the \n";
				$noteText += "         \"Spine_DoNotTouch\" group to this main controller. Instead, it should be parented somewhere \n";
				$noteText += "         outside this control hierarchy, for example, to a parent group node that has its transformations  \n";
				$noteText += "         locked. This ensures that no double-transformations occur in the spline IK. \n";
				text -label $noteText -align left;
				text -label "" -h 10;
				
				setParent..;
			setParent..;
		string $closeButton = `button -label "Close Window" -c "deleteUI dwHelpIKSpineUI"`;
		setParent..;
	
	formLayout -e
		-attachForm $scroll left 0
		-attachForm $scroll top 0
		-attachForm $scroll right 0
		-attachControl $scroll bottom 0 $closeButton
		
		-attachForm $closeButton left 0
		-attachNone $closeButton top
		-attachForm $closeButton right 0
		-attachForm $closeButton bottom 0
		$form;
		
showWindow dwHelpIKSpineUI;
}