//Title:	dwRTClearTextFieldPOPUP.mel
//Author:	David Walden 
//		www.davidwalden.com
//		dwalden74@hotmail.com
//
//Date:		March 29, 2004
//
//Description: Creates a RMB popup menu attached to the given textField which clears the textField.
global proc dwRTClearTextFieldPOPUP(string $textField)
{
popupMenu -b 3 -p $textField;
	menuItem -l "Clear Field" -c ("textField -e -tx \"\" " + $textField + ";");
}