//Title:	dwRTGetDistance.mel
//Author: 	David Walden 
//		www.davidwalden.com
//		dwalden74@hotmail.com
//
//Created: 	March 18, 2004

//Description: Get the distance between two objects. Uses position of objects´ rotate pivot.

global proc float dwRTGetDistance (string $obj1, string $obj2)
{
vector $vector1 = dwRTConvertFloatArrayToVector (`xform -q -ws -rp $obj1`);
vector $vector2 = dwRTConvertFloatArrayToVector (`xform -q -ws -rp $obj2`);

return `mag($vector1 - $vector2)`;
}