//Title:	dwRTValidateName.mel
//Author: 	David Walden
//		www.davidwalden.com
//		dwalden74@hotmail.com
//
//Date:		March 29, 2004
//
//Description: returns 1 if $name is valid, 0 if invalid.
global proc int dwRTValidateName (string $name) 
{
    string $matchingPart = `match "^[a-zA-Z][0-9a-zA-Z_]*$" $name`;
    int $goodMatch = ! `strcmp $matchingPart $name`;
    //  If the two strings are the same, strcmp will return 0

    return $goodMatch;
}